#     _    _                 _ _____ _______   __
#    / \  | | __ _  ___ _ __(_)_   _|_   _\ \ / /
#   / _ \ | |/ _` |/ __| '__| | | |   | |  \ V /
#  / ___ \| | (_| | (__| |  | | | |   | |   | |
# /_/   \_\_|\__,_|\___|_|  |_| |_|   |_|   |_|
#
# See this wiki page for more info:
# https://github.com/jwilm/alacritty/wiki

env:
  TERM: xterm-256color

# Window configurations
window:
  dimensions:
    columns: 0
    lines: 0

  padding:
    x: 10
    y: 10

  decorations: full
  dynamic_title: true
  opacity: 0.8

scrolling:
  multiplier: 1

# Font configurations
font:
  normal:
    family: "JetBrains Mono Nerd Font"
    style: Regular

  bold:
    family: "JetBrains Mono Nerd Font"
    style: Bold

  italic:
    family: "JetBrains Mono Nerd Font"
    style: Italic

  size: 14.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  scale_with_dpi: true

  use_thin_strokes: false

draw_bold_text_with_bright_colors: true

# Colors (Monokai Dark)
schemes:
  # Tokyo Night theme, based on both:
  #   https://github.com/ghifarit53/tokyonight-vim
  #   https://github.com/enkia/tokyo-night-vscode-theme
  tokyo-night: &tokyo-night
    # Default colors
    primary:
      background: '0x1a1b26'
      foreground: '0xa9b1d6'

    # Normal colors
    normal:
      black:   '0x32344a'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan:    '0x449dab'
      white:   '0x787c99'

    # Bright colors
    bright:
      black:   '0x444b6a'
      red:     '0xff7a93'
      green:   '0xb9f27c'
      yellow:  '0xff9e64'
      blue:    '0x7da6ff'
      magenta: '0xbb9af7'
      cyan:    '0x0db9d7'
      white:   '0xacb0d0'

  tokyo-night-storm: &tokyo-night-storm
    # Default colors
    primary:
      background: '0x24283b'
      foreground: '0xa9b1d6'

    # Normal colors
    normal:
      black:   '0x32344a'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan:    '0x449dab'
      white:   '0x9699a8'

    # Bright colors
    bright:
      black:   '0x444b6a'
      red:     '0xff7a93'
      green:   '0xb9f27c'
      yellow:  '0xff9e64'
      blue:    '0x7da6ff'
      magenta: '0xbb9af7'
      cyan:    '0x0db9d7'
      white:   '0xacb0d0'

colors: *tokyo-night
# colors:
#   # selection_background : "#e5e9f0"
#   # selection_foreground : "#2e3440"
#   # url_color : "#d8dee9"
#   # cursor : "#e5e9f0"
#   # active_border_color : "#4c566a"
#   # inactive_border_color : "#3b4252"
#   # active_tab_background : "#2e3440"
#   # active_tab_foreground : "#e5e9f0"
#   # inactive_tab_background : "#3b4252"
#   # inactive_tab_foreground : "#d8dee9"
#   # tab_bar_background : "#3b4252"
#   primary:
#     background : '#2e3440'
#     foreground : '#e5e9f0'
#     # background: '0x282828'
#     # foreground: '0xebdbb2'

#   normal:
#     black:   "#2e3440"
#     red:     "#bf616a"
#     green:   "#a3be8c"
#     yellow:  "#ebcb8b"
#     blue:    "#81a1c1"
#     magenta: "#b48ead"
#     cyan:    "#88c0d0"
#     white:   "#e5e9f0"

#   bright:
#     black:   '0x928374'
#     red:     '0xfb4934'
#     green:   '0xb8bb26'
#     yellow:  '0xfabd2f'
#     blue:    '0x83a598'
#     magenta: '0xd3869b'
#     cyan:    '0x8ec07c'
#     white:   '0xebdbb2'

# Visual bell
bell:
  animation: EaseOutExpo
  duration: 0

# background_opacity: 0.6

selection:
  semantic_escape_chars: ",â”‚`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  faux_scrolling_lines: 1
  hide_when_typing: false

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true

shell:
  program: /bin/zsh

key_bindings:
  - { key: Y,        mods: Control, action: Paste                        }
  - { key: W,        mods: Alt,     action: Copy                         }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Plus,      mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: Return,   mods: Alt,           action: ToggleFullscreen }
  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
  - { key: L,         mods: Control, action: ClearLogNotice                   }
  - { key: L,         mods: Control, chars: "\x0c"                            }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }
